language: node_js
sudo: false
node_js:
- '6'
branches:
  only:
  - master
  - develop
  - "/v\\d+\\.\\d+\\.\\d+?.*/"
env:
  global:
  - GIT_COMMITTER_NAME=travis-ci
  - GIT_COMMITTER_EMAIL=inc@2inc.org
  - GIT_AUTHOR_NAME=travis-ci
  - GIT_AUTHOR_EMAIL=inc@2inc.org
  - secure: QYrqO57tcHLh99+ELoAdM0ojNaPc9cKQ4k8W4oVHOZowxGXKnAnDLYgt/PzmtMnNHmFA/bup+COphLAc7KX5hfcFnLKHlLGq85Rgr6+pzjtXJV+YjROcv0oSNuh2yIjPs52ktAGOqXBEwLMMx3bF8yKQz80idTtrYgJ80bi93f1kUfju+9oXJiOTGV0pehqNfgVC769oYeArGF37luuCeE8T7KHx+tYOqKQwpJcY0HLS086P4HA35sbm4vqtEkrI+UU9xccY9JE1X/NOqNWwR6KP0o1goaYDSXtzN8eMgDfb06jEtEmin//qfWbapg9vfDE352WvUR/n6tKU8fPlkKDBauFxaO4CBkDDJdGJ1cDRaTZH7IjLmfMGVyfAsKAl/36ZBJvGeX6of8PN0fzyHsQHXVsm8P9rJ5449hpsYJmzrBKjagtfC8/tDkD63Xef6jPIMF9p0wtRHUitV2NEcgyzg5wMs5GId1sqHH1wfjLGX7m1eLCcOl8Rw1J5bWabiw0GvymYiHMAu4O4GKmCgz0EkGa1AQt4btGsFjdAcalh7jl9B+EzSDSwG4Vh9V+VBTkimJU92+11R6ZuE719oRee+OljR+3rKSEFP27sTibZUuX1DNYu6UjpRW3ndZEV6MHhR8JOFhcyai0AJFa/UAXsOkaR5DSHLS4YDuk+2wU=
script:
- yarn run gulp build
- yarn run gulp aigis:build
after_success:
- bash ./bin/gh-pages.sh
before_deploy:
- yarn run gulp zip
- ls -la basis.zip
- export RELEASE_FILE=$(ls basis.zip)
deploy:
  provider: releases
  api_key:
    secure: Cf+MKC/38bh7QBoNu6QyiLo7QERwQB8oF0wDV8WIWkPWGJtCsFDgqtJN4f4ofnYfmC4UShvTFegzXJsWgOKwh92XSwkQnYMOC8vqmHw2gVYxdEg9hiQY41X9ANo8DUGMv8L7ZWRgiOzg3V3RqGd4xwaK/ersIs6y3JedCFoUbBqXD/f50msXm8tlO7DiaoMz/NBk0dxoEgbLU2thIiAKLlD96KeoHdv2Edv4jyA/V56eykG/AE5PG7CO8X+HaBJk6ZBin0vMR79eALaR+GwyFhUKjyU5U+Tx5OmhvlMjpLGMS/ysd1JO0/q4tnRLA0/h7wevVi/WyTCrsl08LGBe3ATkRrVVxwxMiODsbS6ZINYN0rP8YmI45MKdZlhfA8shobzJQXvNra11zI32cjLBAePoYZCsYSgb8d5xDgDx9xXO66OqSgicMcOZ/eZvQiTJVWmAUQTovbKdnsjpNGRNOsPoTlPhq0j9IgjAnpdJjgqgLTJfmR0MG6zTyridgcjVWX1FEms084td0J6D0cSi6egwpdj7XzNfbiWuboCmEe2e/9OOsFvXDNfeADAO8MeyH4ghCfTXatJ6JIjAnCvIHcEqKDmuRz0rmj0UqZWf1ZUoFjguq+r7jY+spFloHZFGuLWNEkzBj/gsWCPu8Ptai4Gu/Rj+n1GcmwaXVy9ge1M=
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: sass-basis/basis
